# Azure Pipeline
# Builds docker image and release to DEV

trigger:
  batch: true
  branches:
    include:
      - 'release/*'

variables:
- group: adp-test-variables
- name: DATABASE_URL
  value: postgres://postgres:test@localhost:5432/test

resources:
  containers:
  - container: postgres
    image: postgres:16
    env:
       POSTGRES_PASSWORD: test
       POSTGRES_HOST_AUTH_METHOD: trust
       PGDATA: /var/lib/postgresql/data
    ports:
       - 5432:5432/tcp

services:
  postgres: postgres

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
      versionSpec: '3.13'
      architecture: 'x64'

- script: |
    sudo apt-get install -y libssl-dev
  displayName: 'Install os dependencies'


- script: |
    pip3 install --upgrade pip
    curl -LsSf https://astral.sh/uv/install.sh | sh
  displayName: 'sdist'

- bash: |
    uv build --sdist
    uv export --no-dev --no-emit-project --group image --format requirements-txt > dist/requirements.txt
  displayName: 'building package'

- script: |
    poetry install -vv
  displayName: 'Install dependencies and package'

- script: |
    python -m py.test tests --create-db --junitxml=pytest.xml -vv \
        --cov-report=xml --cov-report=html --cov-report=term \
        --cov-config=tests/.coveragerc \
        --cov=django_temporary_permissions
  env:
    DATABASE_URL: $(DATABASE_URL)
  displayName: 'Run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: "pytest.xml"
    testResultsFormat: 'JUnit'
    testRunTitle: 'Test with Python $(PYTHON_VERSION)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/pytest.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/~build/coverage'
    searchFolder: '$(system.defaultworkingdirectory)/tests'

- bash: |
    echo "##vso[task.setvariable variable=VERSION]"`grep "^VERSION=" docker/Makefile | cut -d "=" -f 2`
  displayName: 'Finding version number'

#- bash: |
#    sed 's/ONBUILD //g' docker/Dockerfile.onbuild  > docker/Dockerfile.full
#    cat docker/Dockerfile.full
#  displayName: 'Generating Dockerfile.full'

- bash: |
      docker build-base \
        ${BUILD_OPTIONS} \
        --build-arg REPO_NAME="${REPO_NAME}" \
        -t kt-django_temporary_permissions/base:${BASE} \
        -f docker/Dockerfile.base  .
      docker build \
        --build-arg CONTAINER_NAME=$(CONTAINER_NAME) \
        --build-arg VERSION=$(VERSION) \
        -t django_temporary_permissions:$VERSION \
        -t django_temporary_permissions:latest \
        -f docker/Dockerfile .
  displayName: 'Build image'

